
name: Diffusion Model CI

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:
    run-on: ubuntu-latest
    strategy:
    matrix: 
      python-version: ["3.10"]
    steps:
    - uses: actions/checkout@v3

    - name: Set up Python ${{ matrix.python-version }}
    uses: actions/setup-python@v4
    with:
      python-version: ${{ matrix.python-version }}

    - name: Install dependencies
    run: |
      python -m pip install --upgrade pip
      pip install -e .[dev]

    - name: Run unit tests
    run: |
      pytest tests/unit --maxfail=5 --disable-warnings --durations=10

    - name: Run integration tests
    run: | 
      pytest tests/integration --maxfail=3 --disable-warnings
    
    - name: Run subsystem tests
    run: |
      pytest tests/subsystems --maxfail=3 --disable-warnings

  experimental:
    runs-on: unbuntu-latest
    continue-on-error: true # <-- experimental failures won't fail the workflow
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with { python-version: "3.11" }
    - run: pip install -e .[test]
    - run: pytest --run-experimental -m experimental


